### ISSUE TITLE
reachedLastPage calculation is wrong

### ISSUE THREAD

**Issue by rakanalh** [nmondollot/NMPaginator#1]
Hello,

This pagination class is loading (total + pageSize) so if your total is 50, 60 items are loaded. My service is returning the count as 50, but when scrolling and reaching 50 it shouldn't load any more but it does.

Looking through the code, you are using:
    return self.page >= (NSInteger)((NSInteger)self.total / (NSInteger)self.pageSize) + 1;

Which if we look at:
total = 50
pageSize = 10

50 / 10 = 5 + 1 = 6
Which makes the class scroll up to 60 items not 50.

My solution is to use ceil when calculating this value:

if(self.total == 0) return NO;
return self.page >= ceil(self.total / self.pageSize);

Which should solve the problem. ceil(50 / 10) = 5. ceil(45 / 10) = 5

At least, this is how i do it. 

Thanks alot for this great component

**Comment by nmondollot** [comment]
Yes, you're absolutely right. My bad.
Here's a proposed solution : 

```
- (BOOL)reachedLastPage
{
    if(self.requestStatus == RequestStatusNone) return NO; // always do the first request
    return self.page >= ceil(self.total/self.pageSize);
}
```

Your solution may break when the search returns 0 result, so I decided to use `self.requestStatus == RequestStatusNone` instead of `self.total == 0`
I'll push it asap. Thank you very much for the feedback!

**Comment by rakanalh** [comment]
I am glad i helped. Thanks again

**Comment by petermumford** [comment]
This still doesn't work. 

If I had 39 rows in my result and 10 items per page it will only show 30 items as it will only show 3 pages but it should show 4 pages. I'm looking to see if I can find a work around.

**Comment by rakanalh** [comment]
It should:

39 / 10 = 3.9 = integer 3
but, ceil(39/10) = 4 = integer 4 pages

**Comment by nmondollot** [comment]
Rakan is right : `ceil(39/10) = 4`, so reachedLastPage should return false if `page = 3`
Your problem may come from a failed http request, or something else. What happens if you trigger `fetchNextPage` manually?
Let me know if you have more information about your issue.

**Comment by petermumford** [comment]
if I do the below in the - (BOOL)reachedLastPage method:
        NSLog(@"self.page[%i], self.total[%i], self.pageSize[%i], ceil[%f]", self.page, self.total, self.pageSize, ceil(self.total/self.pageSize));

I get the below result:
        self.page[1], self.total[39], self.pageSize[10], ceil[3.000000]

**Comment by nmondollot** [comment]
Ok I understand now. You're right, there is a cast problem. It should be `ceil((float)self.total/(float)self.pageSize);` 
I'll push it asap. 
Thanks for the feedback!

**Comment by petermumford** [comment]
I've just seen that by doing some goggling so you beat me to it.

Your welcome. Thank you for sharing this code, very neat!
