### ISSUE TITLE
iOS version support?

### ISSUE THREAD

**Issue by sakares** [nmondollot/NMPaginator#3]
It seem NMPaginator support on iOS5.0+

Are there possible way to implement on iOS4.3+ ?

**Comment by nmondollot** [comment]
Deployment target is actually iOS 4.0, it's supposed to work fine.
(I haven't made tests though)

**Comment by sakares** [comment]
When I try to learn and implement like you code , It seem work fine with iOS4.3+ .

The problem I have found was occured that happen in AppDelegate.m . The ViewController did not enter in 'ViewDidload' or 'ViewDidAppear'. (with iOS4.3 simulator)

**Comment by nmondollot** [comment]
I updated the project to use iOS 5.1 as deployment target. 
Let me know if you still have problems.
