### ISSUE TITLE
How to integrate with Json webservice from php file?

### ISSUE THREAD

**Issue by hafedh** [nmondollot/NMPaginator#4]
Hi, thanks a lot for your job but I wonder if you can explain me how to use your code with a web service from a php file?

I couldn't use the class FlickrPaginator,

**Comment by robertmryan** [comment]
The README touches upon this process of using `NMPaginator`. I found it a little more complicated than that explained, but was able to stumble through, looking at the sample code as a template.

First, as the README says, add `NMPaginator.h` and `NMPaginator.m` to your project, make sure `NMPaginator.m` gets included in the "Compile Sources" in the "Build Phases" of your target's settings, subclass `NMPaginator`, implement your own `fetchResultsWithPage` in your subclass of `NMPaginator` that retrieves data from your web service:

```
#import "MyPaginator.h"

@implementation MyPaginator

- (void)fetchResultsWithPage:(NSInteger)page pageSize:(NSInteger)pageSize
{
    NSString *urlString = [NSString stringWithFormat:@"http://www.yourwebsitehere.com/pagingwebservice?per_page=%1d&page=%1d", pageSize, page];
    NSData *data = [NSData dataWithContentsOfURL:[NSURL URLWithString:urlString]];
    NSError *error;
    NSArray *json = [NSJSONSerialization JSONObjectWithData:data
                                                    options:0
                                                      error:&error];

    [self receivedResults:json total:100]; // I hardcoded 100 records in total ... you'll clearly get this from your server
}

@end
```

Note, for this to compile, I move the declaration of `receivedResults` (below) from `NMPaginator.m` to `NMPaginator.h`. (The author suggests not having the declaration in the .h, but rather add a copy of the declaration in your `NMPaginator` subclass private class extension, but then you get an incomplete implementation warning. I understand why the author suggested what he did, but if he wants a protected method, he should probably have a class extension for that, not do it this way.) Anyway, just move the following line from inside the private class extension in `NMPaginator.m` to inside the interface in `NMPaginator.h`:

```
- (void)receivedResults:(NSArray *)results total:(NSInteger)total;
```

Second, in my view controller I declared `MyPaginator` class and initialized it in `viewDidLoad`. Also declare your view controller to conform to `NMPaginatorDelegate`:

```
@interface ViewController () <NMPaginatorDelegate>

@property (nonatomic, strong) MyPaginator *paginator;

@end
```

Third, in my `viewDidLoad` I initialized it and did the initial fetch (by the way, _make sure the initial pageSize is greater than the number of rows visible on the tableview or else the scrollviewdelegate method might not get called, and thus you'll never fetch more data_):

```
self.paginator = [[MyPaginator alloc] initWithPageSize:12 delegate:self];
[self.paginator fetchFirstPage];
```

Fourth, I changed my tableview's `numberOfRowsInSection` to grab the row count from my paginator:

```
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return [self.paginator.results count];
}
```

Fifth, I changed my `cellForRowAtIndexPath` to also grab the contents from the paginator (obviously, my JSON was an array of dictionaries and one of the keys in my dictionary was "text" ... you'll change this to accommodate your JSON):

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *CellIdentifier = @"Cell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];

    NSDictionary *object = self.paginator.results[indexPath.row];
    cell.textLabel.text = object[@"text"];

    return cell;
}
```

Sixth, implement the Paginator delegate methods in your view controller. This is probably the bare minimum. If you look at the author's example, he does the additional `UIActivityIndicatorView`, which is appropriate ... you should do something like that. Anyway, the delegate methods look like:

```
#pragma mark - Paginator delegate methods

- (void)paginator:(id)paginator didReceiveResults:(NSArray *)results
{
    // update tableview content
    // easy way : call [tableView reloadData];
    // nicer way : use insertRowsAtIndexPaths:withAnimation:
    NSMutableArray *indexPaths = [NSMutableArray array];

    NSInteger i = [self.paginator.results count] - [results count];

    for(NSDictionary *result in results)
    {
        [indexPaths addObject:[NSIndexPath indexPathForRow:i inSection:0]];
        i++;
    }

    [self.tableView beginUpdates];
    [self.tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationMiddle];
    [self.tableView endUpdates];
}

- (void)paginatorDidReset:(id)paginator
{
    [self.tableView reloadData];
}

- (void)paginatorDidFailToRespond:(id)paginator
{
    // Todo
}
```

Seventh and finally, make sure that you have a `UIScrollViewDelegate` method for `scrollViewDidScroll`, that gets more pages if needed:

```
#pragma mark - UIScrollViewDelegate Methods

- (void)scrollViewDidScroll:(UIScrollView *)scrollView {

    // when reaching bottom, load a new page
    if (scrollView.contentOffset.y == scrollView.contentSize.height - scrollView.bounds.size.height)
    {
        // ask next page only if we haven't reached last page
        if(![self.paginator reachedLastPage])
        {
            // fetch next page of results
            [self fetchNextPage];
        }
    }
}

- (void)fetchNextPage
{
    [self.paginator fetchNextPage];
}
```

**Comment by hafedh** [comment]
Thanks a lot robertmryan, I would wish I can get the project source as modified?  I think I have to modify also my webservice PHP file no ? Sorry I've not sufficient exeperience ..

**Comment by robertmryan** [comment]
I wouldn't necessarily recommend trying to use the author's project, but I'd suggest creating your own project, add `NMPaginator.m` and `NMPaginator.h` to it and make the modifications I enumerate above. To download the author's source, click in the "Zip" button at the top of the `NMPaginator` main page. Once you have the source on your machine, you can grab those two files from the project (or edit the author's project if you're determined to do so, but I wouldn't recommend that).

**Comment by robertmryan** [comment]
And, yes, if your web service doesn't already support paging, you'll have to modify that to do so.

**Comment by hafedh** [comment]
Ok thank you Rob, I'll work on paging my web service ..

**Comment by nmondollot** [comment]
Just so you know, I clarified instructions in the readme. It's now possible to use cocoapods.
I didn't get into the specifics of the table view, but rob did a great job explaning it.

I also fixed the compiler warning which was really annoying.

**Comment by robertmryan** [comment]
Excellent all the way around. Thanks!
